export const presetColorSelection = {
  // --- Group A (Bulan_A) ---
  patternA1: {
    id: 'patternA1',
    shape: 'shapeA',
    pattern: 'patternA1',
    image: require('../assets/images/PNGS/Bulan/Bulan_A/Bulan_A1.png'),
    thumb: require('../assets/images/Color/Preset_A1/presetA1.png'),
  },
  patternA2: {
    id: 'patternA2',
    shape: 'shapeA',
    pattern: 'patternA1',
    image: require('../assets/images/PNGS/Bulan/Bulan_A/Bulan_A2.png'),
    thumb: require('../assets/images/Color/Preset_A1/presetA2.png'),
  },
  patternA3: {
    id: 'patternA3',
    shape: 'shapeA',
    pattern: 'patternA1',
    image: require('../assets/images/PNGS/Bulan/Bulan_A/Bulan_A3.png'),
    thumb: require('../assets/images/Color/Preset_A1/presetA3.png'),
  },
  patternA4: {
    id: 'patternA4',
    shape: 'shapeA',
    pattern: 'patternA1',
    image: require('../assets/images/PNGS/Bulan/Bulan_A/Bulan_A4.png'),
    thumb: require('../assets/images/Color/Preset_A1/presetA4.png'),
  },
  patternA5: {
    id: 'patternA5',
    shape: 'shapeA',
    pattern: 'patternA1',
    image: require('../assets/images/PNGS/Bulan/Bulan_A/Bulan_A5.png'),
    thumb: require('../assets/images/Color/Preset_A1/presetA5.png'),
  },
  patternA6: {
    id: 'patternA6',
    shape: 'shapeA',
    pattern: 'patternA1',
    image: require('../assets/images/PNGS/Bulan/Bulan_A/Bulan_A6.png'),
    thumb: require('../assets/images/Color/Preset_A1/presetA6.png'),
  },
  patternA7: {
    id: 'patternA7',
    shape: 'shapeA',
    pattern: 'patternA1',
    image: require('../assets/images/PNGS/Bulan/Bulan_A/Bulan_A7.png'),
    thumb: require('../assets/images/Color/Preset_A1/presetA7.png'),
  },
  patternA8: {
    id: 'patternA8',
    shape: 'shapeA',
    pattern: 'patternA1',
    image: require('../assets/images/PNGS/Bulan/Bulan_A/Bulan_A8.png'),
    thumb: require('../assets/images/Color/Preset_A1/presetA8.png'),
  },

  // --- Group B (Bulan_B) ---
  patternB1: {
    id: 'patternB1',
    shape: 'shapeA',
    pattern: 'patternA2',
    image: require('../assets/images/PNGS/Bulan/Bulan_B/Bulan_B1.png'),
    thumb: require('../assets/images/Color/Preset_B1/presetB1.png'),
  },
  patternB2: {
    id: 'patternB2',
    shape: 'shapeA',
    pattern: 'patternA2',
    image: require('../assets/images/PNGS/Bulan/Bulan_B/Bulan_B2.png'),
    thumb: require('../assets/images/Color/Preset_B1/presetB2.png'),
  },
  patternB3: {
    id: 'patternB3',
    shape: 'shapeA',
    pattern: 'patternA2',
    image: require('../assets/images/PNGS/Bulan/Bulan_B/Bulan_B3.png'),
    thumb: require('../assets/images/Color/Preset_B1/presetB3.png'),
  },
  patternB4: {
    id: 'patternB4',
    shape: 'shapeA',
    pattern: 'patternA2',
    image: require('../assets/images/PNGS/Bulan/Bulan_B/Bulan_B4.png'),
    thumb: require('../assets/images/Color/Preset_B1/presetB4.png'),
  },
  patternB5: {
    id: 'patternB5',
    shape: 'shapeA',
    pattern: 'patternA2',
    image: require('../assets/images/PNGS/Bulan/Bulan_B/Bulan_B5.png'),
    thumb: require('../assets/images/Color/Preset_B1/presetB5.png'),
  },
  patternB6: {
    id: 'patternB6',
    shape: 'shapeA',
    pattern: 'patternA2',
    image: require('../assets/images/PNGS/Bulan/Bulan_B/Bulan_B6.png'),
    thumb: require('../assets/images/Color/Preset_B1/presetB6.png'),
  },
  patternB7: {
    id: 'patternB7',
    shape: 'shapeA',
    pattern: 'patternA2',
    image: require('../assets/images/PNGS/Bulan/Bulan_B/Bulan_B7.png'),
    thumb: require('../assets/images/Color/Preset_B1/presetB7.png'),
  },
  patternB8: {
    id: 'patternB8',
    shape: 'shapeA',
    pattern: 'patternA2',
    image: require('../assets/images/PNGS/Bulan/Bulan_B/Bulan_B8.png'),
    thumb: require('../assets/images/Color/Preset_B1/presetB8.png'),
  },

  // --- Group C (Helang_A) ---
  patternC1: {
    id: 'patternC1',
    shape: 'shapeB',
    pattern: 'patternB1',
    image: require('../assets/images/PNGS/Helang/Helang_A/Helang_A1.png'),
    thumb: require('../assets/images/Color/Preset_C1/presetC1.png'),
  },
  patternC2: {
    id: 'patternC2',
    shape: 'shapeB',
    pattern: 'patternB1',
    image: require('../assets/images/PNGS/Helang/Helang_A/Helang_A2.png'),
    thumb: require('../assets/images/Color/Preset_C1/presetC2.png'),
  },
  patternC3: {
    id: 'patternC3',
    shape: 'shapeB',
    pattern: 'patternB1',
    image: require('../assets/images/PNGS/Helang/Helang_A/Helang_A3.png'),
    thumb: require('../assets/images/Color/Preset_C1/presetC3.png'),
  },
  patternC4: {
    id: 'patternC4',
    shape: 'shapeB',
    pattern: 'patternB1',
    image: require('../assets/images/PNGS/Helang/Helang_A/Helang_A4.png'),
    thumb: require('../assets/images/Color/Preset_C1/presetC4.png'),
  },
  patternC5: {
    id: 'patternC5',
    shape: 'shapeB',
    pattern: 'patternB1',
    image: require('../assets/images/PNGS/Helang/Helang_A/Helang_A5.png'),
    thumb: require('../assets/images/Color/Preset_C1/presetC5.png'),
  },
  patternC6: {
    id: 'patternC6',
    shape: 'shapeB',
    pattern: 'patternB1',
    image: require('../assets/images/PNGS/Helang/Helang_A/Helang_A6.png'),
    thumb: require('../assets/images/Color/Preset_C1/presetC6.png'),
  },
  patternC7: {
    id: 'patternC7',
    shape: 'shapeB',
    pattern: 'patternB1',
    image: require('../assets/images/PNGS/Helang/Helang_A/Helang_A7.png'),
    thumb: require('../assets/images/Color/Preset_C1/presetC7.png'),
  },
  patternC8: {
    id: 'patternC8',
    shape: 'shapeB',
    pattern: 'patternB1',
    image: require('../assets/images/PNGS/Helang/Helang_A/Helang_A8.png'),
    thumb: require('../assets/images/Color/Preset_C1/presetC8.png'),
  },

  // --- Group D (Helang_B) ---
  patternD1: {
    id: 'patternD1',
    shape: 'shapeB',
    pattern: 'patternB2',
    image: require('../assets/images/PNGS/Helang/Helang_B/Helang_B1.png'),
    thumb: require('../assets/images/Color/Preset_D1/presetD1.png'),
  },
  patternD2: {
    id: 'patternD2',
    shape: 'shapeB',
    pattern: 'patternB2',
    image: require('../assets/images/PNGS/Helang/Helang_B/Helang_B2.png'),
    thumb: require('../assets/images/Color/Preset_D1/presetD2.png'),
  },
  patternD3: {
    id: 'patternD3',
    shape: 'shapeB',
    pattern: 'patternB2',
    image: require('../assets/images/PNGS/Helang/Helang_B/Helang_B3.png'),
    thumb: require('../assets/images/Color/Preset_D1/presetD3.png'),
  },
  patternD4: {
    id: 'patternD4',
    shape: 'shapeB',
    pattern: 'patternB2',
    image: require('../assets/images/PNGS/Helang/Helang_B/Helang_B4.png'),
    thumb: require('../assets/images/Color/Preset_D1/presetD4.png'),
  },
  patternD5: {
    id: 'patternD5',
    shape: 'shapeB',
    pattern: 'patternB2',
    image: require('../assets/images/PNGS/Helang/Helang_B/Helang_B5.png'),
    thumb: require('../assets/images/Color/Preset_D1/presetD5.png'),
  },
  patternD6: {
    id: 'patternD6',
    shape: 'shapeB',
    pattern: 'patternB2',
    image: require('../assets/images/PNGS/Helang/Helang_B/Helang_B6.png'),
    thumb: require('../assets/images/Color/Preset_D1/presetD6.png'),
  },
  patternD7: {
    id: 'patternD7',
    shape: 'shapeB',
    pattern: 'patternB2',
    image: require('../assets/images/PNGS/Helang/Helang_B/Helang_B7.png'),
    thumb: require('../assets/images/Color/Preset_D1/presetD7.png'),
  },
  patternD8: {
    id: 'patternD8',
    shape: 'shapeB',
    pattern: 'patternB2',
    image: require('../assets/images/PNGS/Helang/Helang_B/Helang_B8.png'),
    thumb: require('../assets/images/Color/Preset_D1/presetD8.png'),
  },

  // --- Group E (Kapal_A) ---
patternE1: {
  id: 'patternE1',
  shape: 'shapeC',
  pattern: 'patternC1',
  image: require('../assets/images/PNGS/Kapal/Kapal_A/Kapal_A1.png'),
  thumb: require('../assets/images/Color/Preset_E1/presetE1.png'),
},
patternE2: {
  id: 'patternE2',
  shape: 'shapeC',
  pattern: 'patternC1',
  image: require('../assets/images/PNGS/Kapal/Kapal_A/Kapal_A2.png'),
  thumb: require('../assets/images/Color/Preset_E1/presetE2.png'),
},
patternE3: {
  id: 'patternE3',
  shape: 'shapeC',
  pattern: 'patternC1',
  image: require('../assets/images/PNGS/Kapal/Kapal_A/Kapal_A3.png'),
  thumb: require('../assets/images/Color/Preset_E1/presetE3.png'),
},
patternE4: {
  id: 'patternE4',
  shape: 'shapeC',
  pattern: 'patternC1',
  image: require('../assets/images/PNGS/Kapal/Kapal_A/Kapal_A4.png'),
  thumb: require('../assets/images/Color/Preset_E1/presetE4.png'),
},
patternE5: {
  id: 'patternE5',
  shape: 'shapeC',
  pattern: 'patternC1',
  image: require('../assets/images/PNGS/Kapal/Kapal_A/Kapal_A5.png'),
  thumb: require('../assets/images/Color/Preset_E1/presetE5.png'),
},
patternE6: {
  id: 'patternE6',
  shape: 'shapeC',
  pattern: 'patternC1',
  image: require('../assets/images/PNGS/Kapal/Kapal_A/Kapal_A6.png'),
  thumb: require('../assets/images/Color/Preset_E1/presetE6.png'),
},
patternE7: {
  id: 'patternE7',
  shape: 'shapeC',
  pattern: 'patternC1',
  image: require('../assets/images/PNGS/Kapal/Kapal_A/Kapal_A7.png'),
  thumb: require('../assets/images/Color/Preset_E1/presetE7.png'),
},
patternE8: {
  id: 'patternE8',
  shape: 'shapeC',
  pattern: 'patternC1',
  image: require('../assets/images/PNGS/Kapal/Kapal_A/Kapal_A8.png'),
  thumb: require('../assets/images/Color/Preset_E1/presetE8.png'),
},

// --- Group F (Kapal_B) ---
patternF1: {
  id: 'patternF1',
  shape: 'shapeC',
  pattern: 'patternC2',
  image: require('../assets/images/PNGS/Kapal/Kapal_B/Kapal_B1.png'),
  thumb: require('../assets/images/Color/Preset_F1/presetF1.png'),
},
patternF2: {
  id: 'patternF2',
  shape: 'shapeC',
  pattern: 'patternC2',
  image: require('../assets/images/PNGS/Kapal/Kapal_B/Kapal_B2.png'),
  thumb: require('../assets/images/Color/Preset_F1/presetF2.png'),
},
patternF3: {
  id: 'patternF3',
  shape: 'shapeC',
  pattern: 'patternC2',
  image: require('../assets/images/PNGS/Kapal/Kapal_B/Kapal_B3.png'),
  thumb: require('../assets/images/Color/Preset_F1/presetF3.png'),
},
patternF4: {
  id: 'patternF4',
  shape: 'shapeC',
  pattern: 'patternC2',
  image: require('../assets/images/PNGS/Kapal/Kapal_B/Kapal_B4.png'),
  thumb: require('../assets/images/Color/Preset_F1/presetF4.png'),
},
patternF5: {
  id: 'patternF5',
  shape: 'shapeC',
  pattern: 'patternC2',
  image: require('../assets/images/PNGS/Kapal/Kapal_B/Kapal_B5.png'),
  thumb: require('../assets/images/Color/Preset_F1/presetF5.png'),
},
patternF6: {
  id: 'patternF6',
  shape: 'shapeC',
  pattern: 'patternC2',
  image: require('../assets/images/PNGS/Kapal/Kapal_B/Kapal_B6.png'),
  thumb: require('../assets/images/Color/Preset_F1/presetF6.png'),
},
patternF7: {
  id: 'patternF7',
  shape: 'shapeC',
  pattern: 'patternC2',
  image: require('../assets/images/PNGS/Kapal/Kapal_B/Kapal_B7.png'),
  thumb: require('../assets/images/Color/Preset_F1/presetF7.png'),
},
patternF8: {
  id: 'patternF8',
  shape: 'shapeC',
  pattern: 'patternC2',
  image: require('../assets/images/PNGS/Kapal/Kapal_B/Kapal_B8.png'),
  thumb: require('../assets/images/Color/Preset_F1/presetF8.png'),
},
// --- Group G (Kuching_A) ---
patternG1: {
  id: 'patternG1',
  shape: 'shapeD',
  pattern: 'patternD1',
  image: require('../assets/images/PNGS/Kuching/Kuching_A/Kuching_A1.png'),
  thumb: require('../assets/images/Color/Preset_G1/presetG1.png'),
},
patternG2: {
  id: 'patternG2',
  shape: 'shapeD',
  pattern: 'patternD1',
  image: require('../assets/images/PNGS/Kuching/Kuching_A/Kuching_A2.png'),
  thumb: require('../assets/images/Color/Preset_G1/presetG2.png'),
},
patternG3: {
  id: 'patternG3',
  shape: 'shapeD',
  pattern: 'patternD1',
  image: require('../assets/images/PNGS/Kuching/Kuching_A/Kuching_A3.png'),
  thumb: require('../assets/images/Color/Preset_G1/presetG3.png'),
},
patternG4: {
  id: 'patternG4',
  shape: 'shapeD',
  pattern: 'patternD1',
  image: require('../assets/images/PNGS/Kuching/Kuching_A/Kuching_A4.png'),
  thumb: require('../assets/images/Color/Preset_G1/presetG4.png'),
},
patternG5: {
  id: 'patternG5',
  shape: 'shapeD',
  pattern: 'patternD1',
  image: require('../assets/images/PNGS/Kuching/Kuching_A/Kuching_A5.png'),
  thumb: require('../assets/images/Color/Preset_G1/presetG5.png'),
},
patternG6: {
  id: 'patternG6',
  shape: 'shapeD',
  pattern: 'patternD1',
  image: require('../assets/images/PNGS/Kuching/Kuching_A/Kuching_A6.png'),
  thumb: require('../assets/images/Color/Preset_G1/presetG6.png'),
},
patternG7: {
  id: 'patternG7',
  shape: 'shapeD',
  pattern: 'patternD1',
  image: require('../assets/images/PNGS/Kuching/Kuching_A/Kuching_A7.png'),
  thumb: require('../assets/images/Color/Preset_G1/presetG7.png'),
},
patternG8: {
  id: 'patternG8',
  shape: 'shapeD',
  pattern: 'patternD1',
  image: require('../assets/images/PNGS/Kuching/Kuching_A/Kuching_A8.png'),
  thumb: require('../assets/images/Color/Preset_G1/presetG8.png'),
},

// --- Group H (Kuching_B) ---
patternH1: {
  id: 'patternH1',
  shape: 'shapeD',
  pattern: 'patternD2',
  image: require('../assets/images/PNGS/Kuching/Kuching_B/Kuching_B1.png'),
  thumb: require('../assets/images/Color/Preset_H1/presetH1.png'),
},
patternH2: {
  id: 'patternH2',
  shape: 'shapeD',
  pattern: 'patternD2',
  image: require('../assets/images/PNGS/Kuching/Kuching_B/Kuching_B2.png'),
  thumb: require('../assets/images/Color/Preset_H1/presetH2.png'),
},
patternH3: {
  id: 'patternH3',
  shape: 'shapeD',
  pattern: 'patternD2',
  image: require('../assets/images/PNGS/Kuching/Kuching_B/Kuching_B3.png'),
  thumb: require('../assets/images/Color/Preset_H1/presetH3.png'),
},
patternH4: {
  id: 'patternH4',
  shape: 'shapeD',
  pattern: 'patternD2',
  image: require('../assets/images/PNGS/Kuching/Kuching_B/Kuching_B4.png'),
  thumb: require('../assets/images/Color/Preset_H1/presetH4.png'),
},
patternH5: {
  id: 'patternH5',
  shape: 'shapeD',
  pattern: 'patternD2',
  image: require('../assets/images/PNGS/Kuching/Kuching_B/Kuching_B5.png'),
  thumb: require('../assets/images/Color/Preset_H1/presetH5.png'),
},
patternH6: {
  id: 'patternH6',
  shape: 'shapeD',
  pattern: 'patternD2',
  image: require('../assets/images/PNGS/Kuching/Kuching_B/Kuching_B6.png'),
  thumb: require('../assets/images/Color/Preset_H1/presetH6.png'),
},
patternH7: {
  id: 'patternH7',
  shape: 'shapeD',
  pattern: 'patternD2',
  image: require('../assets/images/PNGS/Kuching/Kuching_B/Kuching_B7.png'),
  thumb: require('../assets/images/Color/Preset_H1/presetH7.png'),
},
patternH8: {
  id: 'patternH8',
  shape: 'shapeD',
  pattern: 'patternD2',
  image: require('../assets/images/PNGS/Kuching/Kuching_B/Kuching_B8.png'),
  thumb: require('../assets/images/Color/Preset_H1/presetH8.png'),
},

// --- Group I (Puyuh_A) ---
patternI1: {
  id: 'patternI1',
  shape: 'ShapeE',
  pattern: 'patternE1',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_A/Puyuh_A1.png'),
  thumb: require('../assets/images/Color/Preset_I1/presetI1.png'),
},
patternI2: {
  id: 'patternI2',
  shape: 'ShapeE',
  pattern: 'patternE1',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_A/Puyuh_A2.png'),
  thumb: require('../assets/images/Color/Preset_I1/presetI2.png'),
},
patternI3: {
  id: 'patternI3',
  shape: 'ShapeE',
  pattern: 'patternE1',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_A/Puyuh_A3.png'),
  thumb: require('../assets/images/Color/Preset_I1/presetI3.png'),
},
patternI4: {
  id: 'patternI4',
  shape: 'ShapeE',
  pattern: 'patternE1',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_A/Puyuh_A4.png'),
  thumb: require('../assets/images/Color/Preset_I1/presetI4.png'),
},
patternI5: {
  id: 'patternI5',
  shape: 'ShapeE',
  pattern: 'patternE1',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_A/Puyuh_A5.png'),
  thumb: require('../assets/images/Color/Preset_I1/presetI5.png'),
},
patternI6: {
  id: 'patternI6',
  shape: 'ShapeE',
  pattern: 'patternE1',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_A/Puyuh_A6.png'),
  thumb: require('../assets/images/Color/Preset_I1/presetI6.png'),
},
patternI7: {
  id: 'patternI7',
  shape: 'ShapeE',
  pattern: 'patternE1',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_A/Puyuh_A7.png'),
  thumb: require('../assets/images/Color/Preset_I1/presetI7.png'),
},
patternI8: {
  id: 'patternI8',
  shape: 'ShapeE',
  pattern: 'patternE1',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_A/Puyuh_A8.png'),
  thumb: require('../assets/images/Color/Preset_I1/presetI8.png'),
},

// --- Group J (Puyuh_B) ---
patternJ1: {
  id: 'patternJ1',
  shape: 'ShapeE',
  pattern: 'patternE2',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_B/Puyuh_B1.png'),
  thumb: require('../assets/images/Color/Preset_J1/presetJ1.png'),
},
patternJ2: {
  id: 'patternJ2',
  shape: 'ShapeE',
  pattern: 'patternE2',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_B/Puyuh_B2.png'),
  thumb: require('../assets/images/Color/Preset_J1/presetJ2.png'),
},
patternJ3: {
  id: 'patternJ3',
  shape: 'ShapeE',
  pattern: 'patternE2',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_B/Puyuh_B3.png'),
  thumb: require('../assets/images/Color/Preset_J1/presetJ3.png'),
},
patternJ4: {
  id: 'patternJ4',
  shape: 'ShapeE',
  pattern: 'patternE2',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_B/Puyuh_B4.png'),
  thumb: require('../assets/images/Color/Preset_J1/presetJ4.png'),
},
patternJ5: {
  id: 'patternJ5',
  shape: 'ShapeE',
  pattern: 'patternE2',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_B/Puyuh_B5.png'),
  thumb: require('../assets/images/Color/Preset_J1/presetJ5.png'),
},
patternJ6: {
  id: 'patternJ6',
  shape: 'ShapeE',
  pattern: 'patternE2',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_B/Puyuh_B6.png'),
  thumb: require('../assets/images/Color/Preset_J1/presetJ6.png'),
},
patternJ7: {
  id: 'patternJ7',
  shape: 'ShapeE',
  pattern: 'patternE2',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_B/Puyuh_B7.png'),
  thumb: require('../assets/images/Color/Preset_J1/presetJ7.png'),
},
patternJ8: {
  id: 'patternJ8',
  shape: 'ShapeE',
  pattern: 'patternE2',
  image: require('../assets/images/PNGS/Puyuh/Puyuh_B/Puyuh_B8.png'),
  thumb: require('../assets/images/Color/Preset_J1/presetJ8.png'),
},

// --- Group K (SeriNegeri_A) ---
patternK1: {
  id: 'patternK1',
  shape: 'shapeF',
  pattern: 'patternF1',
  image: require('../assets/images/PNGS/Seri Negeri/SN_A/SN_A1.png'),
  thumb: require('../assets/images/Color/Preset_K1/presetK1.png'),
},
patternK2: {
  id: 'patternK2',
  shape: 'shapeF',
  pattern: 'patternF1',
  image: require('../assets/images/PNGS/Seri Negeri/SN_A/SN_A2.png'),
  thumb: require('../assets/images/Color/Preset_K1/presetK2.png'),
},
patternK3: {
  id: 'patternK3',
  shape: 'shapeF',
  pattern: 'patternF1',
  image: require('../assets/images/PNGS/Seri Negeri/SN_A/SN_A3.png'),
  thumb: require('../assets/images/Color/Preset_K1/presetK3.png'),
},
patternK4: {
  id: 'patternK4',
  shape: 'shapeF',
  pattern: 'patternF1',
  image: require('../assets/images/PNGS/Seri Negeri/SN_A/SN_A4.png'),
  thumb: require('../assets/images/Color/Preset_K1/presetK4.png'),
},
patternK5: {
  id: 'patternK5',
  shape: 'shapeF',
  pattern: 'patternF1',
  image: require('../assets/images/PNGS/Seri Negeri/SN_A/SN_A5.png'),
  thumb: require('../assets/images/Color/Preset_K1/presetK5.png'),
},
patternK6: {
  id: 'patternK6',
  shape: 'shapeF',
  pattern: 'patternF1',
  image: require('../assets/images/PNGS/Seri Negeri/SN_A/SN_A6.png'),
  thumb: require('../assets/images/Color/Preset_K1/presetK6.png'),
},
patternK7: {
  id: 'patternK7',
  shape: 'shapeF',
  pattern: 'patternF1',
  image: require('../assets/images/PNGS/Seri Negeri/SN_A/SN_A7.png'),
  thumb: require('../assets/images/Color/Preset_K1/presetK7.png'),
},
patternK8: {
  id: 'patternK8',
  shape: 'shapeF',
  pattern: 'patternF1',
  image: require('../assets/images/PNGS/Seri Negeri/SN_A/SN_A8.png'),
  thumb: require('../assets/images/Color/Preset_K1/presetK8.png'),
},

// --- Group L (SeriNegeri_B) ---
patternL1: {
  id: 'patternL1',
  shape: 'shapeF',
  pattern: 'patternF2',
  image: require('../assets/images/PNGS/Seri Negeri/SN_B/SN_B1.png'),
  thumb: require('../assets/images/Color/Preset_L1/presetL1.png'),
},
patternL2: {
  id: 'patternL2',
  shape: 'shapeF',
  pattern: 'patternF2',
  image: require('../assets/images/PNGS/Seri Negeri/SN_B/SN_B2.png'),
  thumb: require('../assets/images/Color/Preset_L1/presetL2.png'),
},
patternL3: {
  id: 'patternL3',
  shape: 'shapeF',
  pattern: 'patternF2',
  image: require('../assets/images/PNGS/Seri Negeri/SN_B/SN_B3.png'),
  thumb: require('../assets/images/Color/Preset_L1/presetL3.png'),
},
patternL4: {
  id: 'patternL4',
  shape: 'shapeF',
  pattern: 'patternF2',
  image: require('../assets/images/PNGS/Seri Negeri/SN_B/SN_B4.png'),
  thumb: require('../assets/images/Color/Preset_L1/presetL4.png'),
},
patternL5: {
  id: 'patternL5',
  shape: 'shapeF',
  pattern: 'patternF2',
  image: require('../assets/images/PNGS/Seri Negeri/SN_B/SN_B5.png'),
  thumb: require('../assets/images/Color/Preset_L1/presetL5.png'),
},
patternL6: {
  id: 'patternL6',
  shape: 'shapeF',
  pattern: 'patternF2',
  image: require('../assets/images/PNGS/Seri Negeri/SN_B/SN_B6.png'),
  thumb: require('../assets/images/Color/Preset_L1/presetL6.png'),
},
patternL7: {
  id: 'patternL7',
  shape: 'shapeF',
  pattern: 'patternF2',
  image: require('../assets/images/PNGS/Seri Negeri/SN_B/SN_B7.png'),
  thumb: require('../assets/images/Color/Preset_L1/presetL7.png'),
},
patternL8: {
  id: 'patternL8',
  shape: 'shapeF',
  pattern: 'patternF2',
  image: require('../assets/images/PNGS/Seri Negeri/SN_B/SN_B8.png'),
  thumb: require('../assets/images/Color/Preset_L1/presetL8.png'),
},


};




